name: inception
services:
  nginx:
    build: ./nginx
    init: true
    env_file: .env
    restart: unless-stopped
    networks:
      - my_net
    ports:
      - "443:443"
    volumes:
      - web-files:/home/ecoma-ba/data
    depends_on:
      wordpress:
        condition: service_started
        restart: true
    secrets:
      - server.crt
      - server.key
  wordpress:
    build: ./wordpress
    init: true
    env_file: .env
    restart: unless-stopped
    networks:
      - my_net
    volumes:
      - web-files:/home/ecoma-ba/data
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
  mariadb:
    build: ./mariadb
    init: true
    env_file: .env
    restart: unless-stopped
    networks:
      - my_net
    volumes:
      - db-data:/home/ecoma-ba/data
networks:
  my_net:
      driver: bridge
volumes:
  web-files:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/web
      o: bind
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/data/db
      o: bind
secrets:
  server.crt:
    file: ./secrets/server.crt
  server.key:
    file: ./secrets/server.key
